---
# dataverse/tasks/dataverse-prereqs.yml

- name: install prerequisite packages
  debug:
    msg: '##### INSTALL PREREQUISITE PACKAGES #####'

- name: yum clean all
  shell: 'yum clean all'
  when: ansible_os_family == "RedHat"

- name: let's use the closest centos mirror
  file:
    path: /var/cache/yum/x86_64/7/timedhosts.txt
    state: absent
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: makecache on RedHat
  yum:
    update_cache: yes
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "7"

- name: makecache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: ensure EPEL repository for RedHat7/CentOS7
  yum:
    name: epel-release
    state: latest
  when: ansible_os_family == "RedHat"

- name: install various packages
  package:
    name: bash-completion, git, jq, mlocate, net-tools, sudo, unzip, python3-psycopg2
  tags: prereqs

- name: install java-nnn-openjdk and other packages for RedHat/CentOS.
  yum:
    name: ['java-{{ dataverse.java.version }}-openjdk-devel', 'python36', 'vim-enhanced']
    state: latest
  when: ansible_os_family == "RedHat"
  tags: prereqs

- name: install java-nnn-openjdk and other packages for Debian/Ubuntu.
  package:
    name: default-jdk, python3, vim
  when: ansible_os_family == "Debian"
  tags: prereqs

- name: install ImageMagick on RHEL/CentOS7 for thumbnail generation
  yum:
    name: ImageMagick
    state: latest
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"
    - dataverse.thumbnails
  tags: prereqs

- name: install GraphicsMagic on RHEL/CentOS8 for thumbnail generation
  dnf:
    name: GraphicsMagick
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8"
    - dataverse.thumbnails
  tags: prereqs

- name: install GraphicsMagic on Debian/Ubuntu for thumbnail generation
  package:
    name: graphicsmagick
  when:
    - ansible_os_family == "Debian"
    - dataverse.thumbnails
  tags: prereqs

- name: install curl on Debian/Ubuntu
  package:
    name: curl
  when:
    - ansible_os_family == "Debian"
  tags: prereqs
