---

- name: install rserve
  debug:
    msg: '##### BEGIN RSERVE INSTALLATION #####'

- name: ensure EPEL is installed
  yum:
    name: epel-release
    state: latest
  when: ansible_os_family == "RedHat"

- name: RHEL8 needs codeready-builder
  rhsm_repository:
    name: codeready-builder-for-rhel-8-x86_64-rpms
  when: ansible_distribution == "RedHat" and
        ansible_distribution_major_version == "8"

- name: CentOS8 needs PowerTools
  shell: "dnf config-manager --enable PowerTools"
  when: ansible_distribution == "CentOS" and
        ansible_distribution_major_version == "8"

- name: install base packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - R-core
    - R-core-devel
  when: ansible_os_family == "RedHat"

- name: add keys for R backports for Debian Buster
  apt_key:
    keyserver: keys.gnupg.net
    id: E19F5F87128899B192B1A2C2AD5F960A256A04AF

- name: add backports for Debian Buster to get R 3.6
  apt_repository: repo='deb http://cloud.r-project.org/bin/linux/debian buster-cran35/'
  when:
  - ansible_distribution == "Debian"
  - ansible_distribution_major_version == "10"

- name: install base packages on Debian Buster
  apt:
    name: r-base-core, r-base-dev
    default_release: "buster-cran35"
    state: latest
  when:
  - ansible_distribution == "Debian"
  - ansible_distribution_major_version == "10"

- name: install base packages on Debian/Ubuntu ## we hope bullseye and others will have a good version (Ubuntu 20.04 has R 3.6) -- if not, we will need further handlers for them
  package:
    name: r-base-core, r-base-dev
  when:
  - ansible_os_family == "Debian"
  - ansible_distribution != "Debian" or ansible_distribution_major_version != "10"

- name: detect number of system cores
  set_fact:
    num_cores: '{{ ansible_processor_vcpus }}'

- name: ensure .R exists
  file:
    path: '~/.R'
    state: directory

- name: set in .R/Makevars
  lineinfile:
    path: '~/.R/Makevars'
    line: 'MAKEFLAGS = -j{{ num_cores }}'
    state: present
    create: yes

- name: detect installed R modules
  command: /usr/bin/Rscript --slave --no-save --no-restore-history -e "if (! ('{{item}}' %in% installed.packages()[,'Package'])) print('{{item}}')"
  with_items:
  - R2HTML
  - rjson
  - DescTools
  - Rserve
  - haven
  register: not_installed_r_modules
  changed_when: false                ## this just for registering a variable, it does not change anyting by itself

- name: process module detection output
  set_fact:
    modules_to_install: "{{ not_installed_r_modules.results | map(attribute='stdout') | map('regex_replace','^.* .','')
                            | map('regex_replace','.$','') | select('match', '[a-zA-Z]+') | list }}"

- debug: msg='The following modules are not installed -- {{ modules_to_install }}'

- name: install R modules
  command: /usr/bin/Rscript --slave --no-save --no-restore-history -e "install.packages('{{ item }}', repos=c('https://cloud.r-project.org/', Ncpus='{{ num_cores }}'))"
  with_items: "{{ modules_to_install }}"
  when: modules_to_install is defined

- name: create R user and group
  user:
    name: '{{ rserve.user }}'

- name: install Rserv.conf
  template:
    src: Rserv.conf.j2
    dest: /etc/Rserv.conf
    owner: root
    group: root
    mode: '0644'

- name: install Rserv.pwd
  template:
    src: Rserv.pwd.j2
    dest: /etc/Rserv.pwd
    owner: '{{ rserve.user }}'
    group: '{{ rserve.group }}'
    mode: '0600'

- name: install rserve.service systemd unit file
  template:
    src: rserve.service.j2
    dest: /usr/lib/systemd/system/rserve.service
    owner: root
    group: root
    mode: '0644'

- name: reload systemd, enable rserve, start
  systemd:
    name: rserve
    enabled: yes
    daemon_reload: yes
    state: started
