---

- name: rhel and centos 8 don't play nice with postgresql9.6
  set_fact:
    die: "RHEL/CentOS8's psycopg2 isn't backwards-compatible with PostgresQL 9.6. Use PostgresQL 10 or higher."
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "8"
    - db.postgres.version < 10

- name: debian version check
  set_fact:
    die: "from Debian OS family, only debian version 10 is supported (but you are welcome to try others by commenting this out)"
  when:
    - ansible_os_family == "Debian"
    - ansible_distribution != "Debian"
    - ansible_distribution_major_version != "10"

- name: squawk
  debug:
    msg: '{{ die }}'
  when: die is defined

- name: bail
  meta: end_play
  when: die is defined
